#!/bin/sh

#class color
kuning='\e[33;1m'
biru='\e[34;1m'
merah='\e[31;1m'
putih='\e[37;1m'
tutup='\e[39;1m'
clear
echo "";
echo  $merah
echo  "
 ██████╗ ██████╗ ███████╗██████╗      _______________________________
 ██╔══██╗██╔══██╗██╔════╝██╔══██╗    |                               |
 ██████╔╝██████╔╝█████╗  ██████╔╝    | Author : -$tutup$putih Sn1perXploit20     $tutup$merah|$tutup$putih
 ██╔══██╗██╔══██╗██╔══╝  ██╔══██╗    $tutup$merah|          -$tutup$putih Yoshieichiro_01 $tutup$merah   |$tutup$putih
 ██████╔╝██║  ██║██║     ██████╔╝    $tutup$merah|          -$tutup$putih ZakirDotID $tutup$merah        |$tutup$putih
 ╚═════╝ ╚═╝  ╚═╝╚═╝     ╚═════╝     $tutup$merah|_______________________________|$tutup	
";

# class warna
echo  "$kuning ======bruteforce facebook====== $tutup"
echo  "$kuning ======$tutup\e[34;1mfb.com/otakuhacking$tutup$kuning======$tutup"
echo  "$kuning ======Powered by X20Coder====== $tutup"	
hijau='\e[32;1m';

echo "";
echo  $hijau

read -p 'Enter username / facebook id : ' un
read -p 'Enter wordlist directory : ' pw
perl /usr/share/brfacebook/brf $un $pw